name: Shared Infrastructure CD Flow

on:
  workflow_run:
    workflows: ["Shared Infrastructure CI Flow"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-to-production:
    name: Deploy Shared Infrastructure to Production Server
    runs-on: self-hosted

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy Locally on Self-Hosted
        run: |
          set -e
          cd /Users/hork/Downloads/GitOps-Manifest/
          gmake up-infra
